stages:
  - build
  - warnconv
  - test
  - memleaks

.build_template: &build_definition
  stage: build
  script:
    - cmake -E make_directory build
    - cd build
    - cmake -F "Unix Makefiles" ..
    - make

mscbdecomp_Jessie:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:jessie-gfortran-blas-lapack
  <<: *build_definition

mscbdecomp_Buster:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-gfortran-blas-lapack
  <<: *build_definition
  
mscbdecomp_Stretch:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gfortran-blas-lapack
  <<: *build_definition

mscbdecomp_Jessie_OpenBlas:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:jessie-gfortran-openblas-lapack
  <<: *build_definition

mscbdecomp_Stretch_OpenBlas:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gfortran-openblas-lapack
  <<: *build_definition

mscbdecomp_CentOS:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:centos-7-gfortran-blas-lapack
  <<: *build_definition

mscbdecomp_OpenSuse-13.2:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-13.2-gfortran-blas-lapack
  <<: *build_definition

mscbdecomp_OpenSuse-42.1:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-42.1-gfortran-blas-lapack
  <<: *build_definition

mscbdecomp_Stretch_PGI1710:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-pgi1710-cmake-blas-lapack-fftw-hdf5-scipy
  type: build
  script:
    - cmake -E make_directory build
    - cd build
    - export PGI=/opt/pgi
    - export PATH=/opt/pgi/linux86-64/17.10/bin:$PATH
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_Fortran_COMPILER=pgfortran -DCMAKE_CXX_COMPILER=pgc++ ..
    - cmake --build . --target mscbdecomp --config Release

mscbdecomp_Ubuntu_Trusty:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/ubuntu:trusty-tahr-gfortran-lapack
  <<: *build_definition

mscbdecomp_Ubuntu_Xenial:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:xenial-gfortran-lapack
  <<: *build_definition

mscbdecomp_Ubuntu_Bionic:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/ubuntu:bionic-beaver-gfortran-lapack
  <<: *build_definition

